# Generated by Django 2.1.5 on 2019-01-30 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletask',
            name='task',
            field=models.CharField(default='EMPTY_TASK', max_length=200),
        ),
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(default='MY_LIST', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 19, 53, 12, 389429)),
        ),
    ]
