# Generated by Django 2.1.5 on 2019-02-04 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0003_auto_20190204_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 18, 23, 36, 531208)),
        ),
    ]
