# Generated by Django 2.1.5 on 2019-02-26 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0005_auto_20190206_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmationKey',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='singletask',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toDo.ToDoList'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 10, 0, 33, 542759)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='toDo.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
