# Generated by Django 2.1.5 on 2019-02-26 10:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0007_auto_20190226_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singletask',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toDo.ToDoList'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 10, 20, 40, 12342)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='toDo.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
